import { palette, typography, space, radius, elevation, blur, zIndex } from "./tokens";
import { duration, ease, loop } from "./motion";

const block = (sel: string, vars: Record<string, string | number>, extra = "") =>
  `${sel} {\n${Object.entries(vars).map(([k, v]) => `  --${k}: ${v};`).join("\n")}\n${extra}}\n`;

const prefixed = (p: string, o: Record<string, string | number>) =>
  Object.fromEntries(Object.entries(o).map(([k, v]) => [`${p}-${k}`, v]));

/** Compiles tokens.ts + motion.ts into CSS custom properties. */
export function renderTokensCss(): string {
  const shared = {
    ...prefixed("fs", typography.scale),
    ...prefixed("lh", typography.leading),
    ...prefixed("tr", typography.tracking),
    ...prefixed("sp", space),
    ...prefixed("r", radius),
    ...prefixed("blur", blur),
    ...prefixed("z", Object.fromEntries(Object.entries(zIndex).map(([k, v]) => [k, String(v)]))),
    ...prefixed("dur", Object.fromEntries(Object.entries(duration).map(([k, v]) => [k, `${v}ms`]))),
    ...prefixed("ease", Object.fromEntries(Object.entries(ease).map(([k, v]) => [k, `cubic-bezier(${v.join(", ")})`]))),
    ...prefixed("loop", Object.fromEntries(Object.entries(loop).map(([k, v]) => [k, `${v}ms`]))),
    "ff-display": typography.families.display,
    "ff-text": typography.families.text,
    "ff-mono": typography.families.mono,
    "display-weight": "800",
  };
  const darkElevation = Object.fromEntries(
    Object.entries(elevation).map(([k, v]) => [k, v.replaceAll("rgba(26,23,18", "rgba(0,0,0")]),
  );
  return [
    "/* GENERATED by scripts/build-tokens.ts from src/design/tokens.ts + motion.ts — do not edit. */\n",
    block(":root", { ...shared, ...prefixed("c", palette.light), ...prefixed("el", elevation) }, "  color-scheme: light;\n"),
    block(':root[data-theme="dark"]', { ...prefixed("c", palette.dark), ...prefixed("el", darkElevation) }, "  color-scheme: dark;\n"),
    block("@media (prefers-reduced-motion: reduce) {\n  :root:not([data-motion=\"full\"])", {
      "dur-fast": "1ms", "dur-base": "150ms", "dur-slow": "150ms", "dur-slower": "150ms", "dur-cinematic": "150ms",
    }) + "}\n",
    block(':root[data-motion="reduced"]', {
      "dur-fast": "1ms", "dur-base": "150ms", "dur-slow": "150ms", "dur-slower": "150ms", "dur-cinematic": "150ms",
    }),
  ].join("\n");
}
